services:
  redis:
    image: redis:latest
    container_name: wefood-redis
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - wefood-network
      
  postgres:
    image: postgres:13
    container_name: wefood-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wefood
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wefood-network
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: wefood-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - wefood-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: wefood-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
      - wefood-network
networks:
  wefood-network:
    name: wefood-network
    driver: bridge
volumes:
  postgres_data:
  redis_data:
  