# Configuração do eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # onde o eureka ta rodando
      defaultZone: http://localhost:8084/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8081
spring:
  cloud:
    # Habilitar o discovery (Mostrar as instancias)
    discovery:
      enabled: true
      # Desabilita o config server (Configs em outro repo)
    config:
      uri: http://127.0.0.1:8889
      enabled: false
  application:
    name: payment-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/wefood
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

