eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-ms:8084/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  cloud:
    discovery:
      enabled: true
      # Desabilita o config server (Configs em outro repo)
    config:
      uri: http://127.0.0.1:8889
      enabled: false
  application:
    name: pedido-ms
  datasource:
    url: jdbc:postgresql://postgres:5432/wefood
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  redis:
      host: redis
      port: 6379
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
feign:
  client:
    profile:
      url: http://profile-ms:8083/
